name: Deploy to Env

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set NPM Registry identity
        uses: ohoareau/actions/npmrc-scope-authtoken-add@master
        with:
          scope: genstackio
          token: ${{secrets.CUSTOM_NPM_TOKEN}}
          registry: registry.npmjs.org

      - name: Set Env from current Branch
        uses: ohoareau/actions/branch-to-env@master
        with:
          secrets: ${{toJson(secrets)}}
          branch: ${{github.base_ref}}

      - name: Set some env vars from forced env (dev)
        uses: ohoareau/actions/env-vars-from-env@master
        with:
          secrets: ${{toJson(secrets)}}
          env: dev

      - name: Install
        shell: 'script -q -e -c "bash {0}"'
        run: make install
        env:
          FORCE_COLOR: 3
          CI: true

      - name: Test
        shell: 'script -q -e -c "bash {0}"'
        run: make test
        env:
          FORCE_COLOR: 3
          CI: true

      - name: Add AWS Account Profile (default)
        uses: ohoareau/actions/aws-account-profile-add@master
        with:
          name: default
          aki: ${{secrets.AWS_DEPLOY_ACCOUNT_ACCESS_KEY_ID}}
          sak: ${{secrets.AWS_DEPLOY_ACCOUNT_SECRET_ACCESS_KEY}}

      - name: Add AWS Role Profile
        uses: ohoareau/actions/aws-role-profile-add@master
        with:
          name: genstackio-${{env.env}}
          source: default
          role: ${{env.AWS_DEPLOY_ACCOUNT_ROLE_ARN}}

      - name: Deploy
        shell: 'script -q -e -c "bash {0}"'
        run: make deploy env=${{env.env}}
        env:
          FORCE_COLOR: 3
          CI: true

      - name: Migrate
        shell: 'script -q -e -c "bash {0}"'
        run: make migrate env=${{env.env}}
        env:
          FORCE_COLOR: 3
          CI: true

